# Generated by Django 2.1 on 2018-08-22 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
